ory/web

.github/workflows/publish.yml, static/_redirects
=> ci: do not comment on commits

README.md
=> docs: replace netlify with github actions badge

src/pages/oathkeeper.tsx
=> fix: Add keywords to Oathkeeper landing

src/config.tsx, src/pages/oathkeeper.tsx
=> fix: add keywords to project config

.github/PULL_REQUEST_TEMPLATE.md
=> fix: correct typo in pr template

src/pages/markdown/imprint.md
=> fix: updated Ory Corp company address

src/components/blog-summary-section.module.css
=> fix: responsive behaviour of blog-summary-section.tsx

src/styles/global.css
=> fix: give youtube embed 100% max-width

package.json
=> fix: increase stack size for build.js

src/pages/blog/modern-application-architecture.md
Blog post about modern application architecture by Lee Atchison
**Links**
=> feat(blog): app architecture

src/config.tsx, src/pages/kratos.tsx
=> fix: remove left seperators 'l-sep' from config.tsx and kratos.tsx

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/semantic.yml, .github/workflows/closed_references.yml, .github/workflows/labels.yml, .github/workflows/stale.yml, CONTRIBUTING.md, LICENSE, SECURITY.md
Updated repository templates to https://github.com/ory/meta/commit/01a6e59075cbe305ebd179bbaa9e76129b791337.
=> chore: update repository template to 01a6e590

src/pages/blog/kratos-knative-demo.md
Fixed headlines on the knative guide, they were too big.
the changes.
=> blog: fixed headlines guide

src/pages/blog/choose-recommended-argon2-parameters-password-hashing.md, src/pages/blog/golang-go-code-coverage-accurate.md, src/pages/blog/kratos-knative-demo.md, src/pages/blog/run-oauth2-server-open-source-api-security.md, src/pages/blog/why-new-user-login-registration.md, src/pages/oathkeeper.tsx
Small typo fixes
the changes.
- [] I have added necessary documentation within the code base (if appropriate)
=> docs: fixes small typos

static/_redirects
=> fix: broken links identified by Sistrix

src/pages/keto.tsx
Link to keto sdk was broken.
the changes.
=> fix: link to keto sdk

static/_redirects
redirected 404 Error links.
the changes.
=> fix: broken links identified by Netlify

build.js, src/components/adopters.module.css.d.ts, src/components/announcement.module.css.d.ts, src/components/blog-hero.module.css.d.ts, src/components/blog-section.module.css.d.ts, src/components/blog-summary-section.module.css.d.ts, src/components/codebox.module.css.d.ts, src/components/collaborator.module.css.d.ts, src/components/compressed-hero.module.css.d.ts, src/components/compressed-section.module.css.d.ts, src/components/footer.module.css.d.ts, src/components/header.module.css.d.ts, src/components/hero.module.css.d.ts, src/components/mobile-menu.module.css.d.ts, src/components/newsletter.module.css.d.ts, src/components/profile.module.css.d.ts, src/components/projects.module.css.d.ts, src/components/responsive-section.module.css.d.ts, src/components/section.module.css.d.ts, src/components/stats.module.css.d.ts, src/components/team.module.css.d.ts, src/components/thin-project.module.css.d.ts, src/components/vertical-divider.module.css.d.ts, src/pages/blog.module.css.d.ts, src/pages/index.module.css.d.ts, src/styles/global.css.d.ts, src/styles/grid.css.d.ts, src/styles/typography.css.d.ts
=> fix: remove v1 docs

src/pages/blog/kratos-knative-demo.md
The link was incomplete
the changes.
works.
appropriate).
=> fix: broken link knative article

src/components/blog-section.module.css
- figure captions now have a margin-top
=> fix: minor aesthetic changes

src/pages/blog/account-recovery-password-reset-rethinking-user-accountability.md
I fixed the formatting and added the header.
I will look into the contents more, maybe we can talk tomorrow more about it.
=> docs: blogpost kratos accountability 

static/_redirects
the changes.
works.
appropriate).
=> fix: resolve broken redirects

src/components/profile.tsx
Closes #89
the changes.
works.
appropriate).
=> fix: broken profile images

src/pages/blog/run-oauth2-server-open-source-api-security.md
Embedded the hydra quickstart video. 
I wrote something to make it clear that this is not a video of this guide but a very similar one?
the changes.
works.
appropriate).
=> docs: blog add hydra video

src/components/layout.tsx, src/pages/hydra.tsx, src/pages/keto.tsx, src/pages/kratos.tsx, src/pages/oathkeeper.tsx
the changes.
works.
appropriate).
=> feat: move to new gh discussions

src/components/stats.tsx, src/pages/blog/run-oauth2-server-open-source-api-security.md
the changes.
works.
appropriate).
=> feat: add more repos to counter

src/pages/blog/kratos-react-native.mdx
the changes.
works.
appropriate).
=> fix: update package names to @ory

src/components/large-feature.module.css, src/components/large-feature.module.css.d.ts, src/components/large-feature.tsx
- add large-feature.tsx component
- has following proptypes:
```
<LargeFeature
//add `alternate` to switch visual content from right to left, and vice-versa
//add `openInNewWindow: true` to make redirects open in new tabs
title={''}
description={''}
learn={''}
href={''}
visual={''}
/>
```
=> feat: add new large-feature.tsx

src/components/highlights.module.css, src/components/highlights.tsx
- fix css responsiveness
- set proper margins
=> feat: edit highlights.tsx to include icons and appearance

static/_redirects
- rempove ory.sh/products to ory.sh redirect
- alter ory.am/products redirect to now point to ory.sh/products
- fixes #137
=> fix: fix redirect from ory.sh/products to ory.sh and fix #137

src/templates/blog.tsx
fix appearance of blogpost newsletter component and add paragraph about updates
=> fix: fix appearance of blogpost newsletter 

src/pages/markdown/ptos.md
create a new page for the preview agreement and terms for the use of the Ory cloud preview
=> feat: create new page preview agreement

src/pages/markdown/ptos.md
Test PR to see #151 on netlify
Fix the list of requirements in section 2.2c of the Preview Terms of Service Agreement. Was not rendering correctly.
the changes.
works.
appropriate).
=> fix: requirements list in section 2.2C

src/pages/blog/kratos-react-native.mdx
the changes.
works.
appropriate).
=> docs: update react native prod values

src/components/adopters.module.css, src/components/codebox.module.css, src/components/quicklinks.module.css, src/pages/blog/kratos-react-native.mdx, src/pages/developer.tsx, src/pages/markdown/ptos.md
Updated repository templates to https://github.com/ory/meta/commit/c704df8ef4892cb97ccfe968c2300280ed58c055.
=> chore: update repository template to c704df8e

src/pages/blog/keto-zanzibar-evolution.md
the changes.
works.
appropriate).
=> docs: keto v0.6 article (#166)

src/components/next/freestanding/button/button.module.css, src/components/next/freestanding/button/button.tsx, src/components/next/freestanding/colour/colour-wrapper.tsx, src/components/next/freestanding/molecule/molecule-icon-wrapper.module.css, src/components/next/freestanding/molecule/molecule-icon-wrapper.tsx, src/components/next/freestanding/styling/styling.tsx, src/components/next/layouts/faq/faq.module.css, src/components/next/layouts/faq/faq.tsx, src/components/next/layouts/featurelist/content/feature-list-content.tsx, src/pages/next/pricing.tsx
the changes.
works.
appropriate).
=> fix: icons & link font

src/components/next/freestanding/containers/container.tsx, src/components/next/layouts/quotes/quotes.tsx
the changes.
works.
appropriate).
=> fix: sm & xs quotes

src/components/next/layouts/layout/layout.tsx, src/pages/next/index.tsx, src/pages/next/pricing.tsx
the changes.
works.
appropriate).
=> fix: link descriptions

src/components/blog-hero.module.css, src/components/blog-section.module.css, src/components/freestanding/button/button.module.css, src/pages/blog.tsx
Fix blog padding from nav.
Fix button borders moving divs.
the changes.
works.
appropriate).
=> fix: styles

src/components/freestanding/containers/container.module.css, src/components/freestanding/dropdown/dropdown-item.tsx, src/components/freestanding/dropdown/dropdown-menu.module.css, src/components/freestanding/dropdown/dropdown-mobile-item.module.css, src/components/freestanding/dropdown/dropdown-mobile-item.tsx, src/components/freestanding/dropdown/dropdown-mobile-menu.module.css, src/components/freestanding/dropdown/dropdown-mobile-menu.tsx, src/components/freestanding/dropdown/menu-item.tsx, src/components/layouts/navigation/navigation.module.css, src/components/layouts/navigation/navigation.tsx
Fixes the navigation hide on scroll (desktop & mobile).
Correctly overflows content into a scroll for mobile.
Switch CTA on mobile NAV to top.
the changes.
works.
appropriate).
=> fix: navigation

gatsby-config.js
the changes.
works.
appropriate).
=> fix: use np.min.js

src/components/team.tsx
modified the mission in the About Us...
the changes.
works.
appropriate).
=> fix: Update team.tsx

gatsby-config.js
Resolves broken configuration introduced in https://github.com/ory/web/commit/7abf9365c6b1f8119420ee5e3dbfc94dfe053c84
/cc @vinckr please check your code in the IDE as it will flag such malformed entries and also format the code to detect incorrect indentation which hints at, for example, broken configs!
=> fix: malformed config

src/components/layouts/layout/layout.tsx, src/components/layouts/quickstart/quickstart-content.tsx, src/pages/index.tsx, src/pages/pricing.tsx
the changes.
works.
appropriate).
=> fix: replace get started with request access

src/pages/index.tsx, src/pages/pricing.tsx
As per https://github.com/ory-corp/product/issues/160, there was one on the pricing page and further down on landing that have been changed to "Request Acccess". 
the changes.
works.
appropriate).
=> fix: cta's

src/pages/blog/looking-at-keto.md
=> fix: typo on "looking at keto" blog post

src/components/layouts/layout/layout.tsx
https://github.com/ory/web/issues/230
the changes.
works.
appropriate).
=> fix: uniform about us

src/pages/hydra.tsx, src/pages/index.tsx, src/pages/keto.tsx, src/pages/kratos.tsx, src/pages/oathkeeper.tsx
Signed-off-by: jfcurran <john@ory.sh>
#225 partially, regarding image sizes
add `className="responsive"` to images
=> fix: add class="responsive" to images on open-source pages and index

src/components/layouts/adopters/adopters-content.tsx, src/pages/hydra.tsx, src/pages/index.tsx, src/pages/keto.tsx, src/pages/kratos.tsx, src/pages/oathkeeper.tsx
closes https://github.com/ory/web/issues/243
=> fix: image alts

src/components/layouts/adopters/adopters-content.tsx, src/components/layouts/hero/hero.tsx, src/components/layouts/layout/layout.tsx, src/pages/hydra.tsx, src/pages/index.tsx, src/pages/keto.tsx, src/pages/kratos.tsx, src/pages/oathkeeper.tsx
https://github.com/ory/web/pull/249 redone on web branch
The change from #248 had to be included for styling.
If that PR needs changes I can change it here accordingly, but the layout was important for both.
Read more about my reasons for these changes here: ory-corp/product#151 (comment)
=> feat: OS pages content & hero landing page layout 

src/pages/index.tsx
as discussed in 
https://github.com/ory-corp/product/issues/170
=> fix: landing page hero

src/components/layouts/layout/layout.tsx
This is 
moving the blog from the "company" tab where its hard to find intuitively to the developer tab
+
shortening the descriptions a little bit so it looks smoother overall
=> fix: move blog

static/_redirects
=> fix: add correct redirect

src/pages/markdown/privacy.md
We only use matomo to collect analytics about the website, changed the privacy notice to reflect that.
=> docs: privacy update

src/styles/global.css
the changes.
works.
appropriate).
=> fix: improve css rules for better image sharpness

src/pages/503.tsx
confirm that I got the green light (please contact
the changes.
works.
appropriate).
=> feat: 503 page

src/pages/blog/run-oauth2-server-open-source-api-security.md
the changes.
works.
appropriate).
=> docs: update hydra blog post

gatsby-config.js
the changes.
works.
appropriate).
=> fix: sitemap url

src/styles/global.css
the changes.
works.
appropriate).
=> fix: do not use contrast image on apple

src/pages/about.tsx
=> fix: Update about.tsx

src/components/layouts/team/team-members.tsx
=> fix: Update team-members.tsx

src/components/layouts/layout/layout.tsx
=> fix: typos / remove we're hiring span from Jobs

src/page-content/shared/content-team.tsx
diff should be self-explanatory
Or is there a web link that should be here instead?
=> fix: remove de.linkedin.com link

src/page-content/content-jobs.tsx
Suggesting some edits, some basic typo fixes, others for tonality/word choice/flow.
the changes.
works.
appropriate).
=> fix: many textual aspects of jobs page

src/markdown/jobs/execassist.mdx
Did Lisa Heinert fill this role, or are we still searching?
the changes.
works.
appropriate).
=> feat: can we delete this job posting?

src/markdown/blog/kratos-react.mdx, src/page-content/events/content-summit-21.tsx
part of an ory.sh blog post
the changes.
works.
appropriate).
=> fix:  envvar 'katos' to 'kratos'

src/markdown/blog/orymanifesto.mdx
sorry guys this man named Simon Jones gave all this intense commentary on the manifesto and said this was a typo- but i re-read and it's not so i'm changing it back. 
communication is singular noun, preceded by 3 adjectives, so it's correct as singular third person "is."
the changes.
works.
appropriate).
=> fix again: typo in manifesto 

src/page-content/pricing-tiers/pricing-cloud.tsx
Changing this link from :mailto to link for scheduling a meeting via hubspot.
=> chore: change button link to Hubspot Meeting and Free Plan Form

src/markdown/release-notes/2022-02.md, src/page-content/content-release-notes.tsx
=> chore: updated text

src/page-content/content-cloud.tsx, src/page-content/pricing-tiers/pricing-cloud.tsx
Removing Forms from Developer and Startup Plan
=> chore: Updating pricing page

src/markdown/release-notes/2022-02.md
=> chore: Changed the Markdown file

src/page-content/navigation/navigation-announcement.tsx
the changes.
works.
appropriate).
=> fix: adding-Startplan-announcment-to-web

src/components/layouts/banner/banner.module.css.d.ts, src/components/layouts/release-notes/release-list.module.css.d.ts, static/scripts.js
- added host filter to only run the script on production; GA traffic is being bloated by CI traffic, see screenshot
- added gtag wrapper for dataLayer
- added support for GTM consent mode and set defaults
the changes.
works.
appropriate).
=> fix: gtm container initialization

src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
=> chore: review and edit

src/markdown/blog/ory-series-a-funding-update.mdx, src/markdown/jobs/brand-and-content-marketing-manager.mdx, src/markdown/jobs/data-scientist.mdx, src/markdown/jobs/developer-advocate.mdx, src/markdown/jobs/developer-relations-intern.mdx, src/markdown/jobs/executive-assistant.mdx, src/markdown/jobs/frontend-development.mdx, src/markdown/jobs/full-stack-development.mdx, src/markdown/jobs/product-marketing-manager.mdx, src/markdown/jobs/sales-development-representative.mdx, src/markdown/jobs/sdk-maintainer.mdx, src/markdown/jobs/senior-performance-marketing-manager.mdx, src/markdown/jobs/senior-technical-seo-marketing-manager.mdx, src/markdown/jobs/shared.tsx, src/markdown/jobs/solutions-engineering.mdx, src/markdown/jobs/systems-reliability-engineering.mdx, src/markdown/jobs/talent-acquisition-manager.mdx, src/markdown/jobs/uxdesigner.mdx, src/markdown/senior-technical-seo-marketing-manager.mdx
- fix: streamline jobs postings
- fix: add talent am job
the changes.
works.
appropriate).
=> fix: update jobs

src/page-content/shared/content-quotes.tsx
Hey! Thanks for including my quote on your site ☺️ I'm a little ashamed to admit that I made a mistake in it so this PR addresses that.
This is a previously unknown bug (that would only be seen by absolute pedants) and there is no related issue.
the changes.
works.
appropriate).
=> fix: add missing word to quote and title

src/page-content/navigation/header.json
the changes.
works.
appropriate).
=> fix: move pricing in navigation

src/markdown/release-notes/2022-03.md
Added the march release notes to the page.
=> feat: Cloud release notes update

src/markdown/blog/student-sharing-platform-open-source-auth.mdx
Fix the formatting of a codeblock
=> Fix codeblock formatting
